### PR TITLE
Added Student Deactivation Feature

### PR DESCRIPTION
**Pull request by yudisupriyadi123**
This PR is taken from issue #2.

- Added student de-activation feature (template and logic)
- Added student re-activation feature (template and logic)
- Change login to show prompt "deactivated student should re-activate his account before login"
- Change login template to show re-activation link
- Filter student list on new/edit task to active student only

### CODE REVIEW

**Comment by marceloFA** [comment]
Yes, we still need to pass the correct queryset to the TaskForm so then only active students will be on the list

**Comment by marceloFA** [comment]
Did you implement any mechanism of REactivating a student account? Could you do it if you ahven't already?
 Let's suppose i deactivated my account, following this I must be able to activate my account again

**Comment by marceloFA** [comment]
One third thing is that i'd like the `is_acative` field on the Student model to be a ´BooleanField´. In my opition it's more readable.
Would be able to work in this change? @yudisupriyadi123

**Comment by yudisupriyadi123** [comment]
> Yes, we still need to pass the correct queryset to the TaskForm so then only active students will be on the list.
> It seems the queryset would be like `queryset=Student.objects.filter(is_active=1)`
> Can you do this, @yudisupriyadi123?

> Did you implement any mechanism of REactivating a student account? Could you do it if you haven't already?
> Let's suppose I deactivated my account, following this I must be able to activate my account again

I will try.

> One third thing is that i'd like the `is_acative` field on the Student model to be a ´BooleanField´. In my opition it's more readable.
> Would be able to work in this change? @yudisupriyadi123

Okay I will change it.

**Comment by marceloFA** [comment]
I've seen that you updated the pull request, @yudisupriyadi123 .That's some great work!

Would you lastly update the PR Description so as we can clearly understand all the changes?

**Comment by yudisupriyadi123** [comment]
@marceloFA Thank you! 

This is my first contribution, how PR Description format should be?

**Comment by marceloFA** [comment]
The title is just fine like this. I need you to update the PR description. It should contain all changes you did on this PR

**Comment by marceloFA** [comment]
What an incredible job, thanks so much for helping out!

**Comment by yudisupriyadi123** [comment]
You're welcome. Thank you! @marceloFA

**Pull request merged**
