### PR TITLE
Added password reset

### PR DESCRIPTION
**Pull request by bsr3000**
Hello, sorry I didn't write that I would like to take that issue in related GH-1 

* Used `django.contrib.auth` ready endpoints
* Added related templates

### CODE REVIEW

**Comment by marceloFA** [comment]
What a nice work !! I've reviewed the PR and it seems just fantastic. I suppose now we need new Student instances to have an email field, so then the password reset feature can work propely, isn't it the case?

**Comment by bsr3000** [comment]
@marceloFA Basically, you extend `AbstractUser` and it already has `email` field :)

**Comment by marceloFA** [comment]
Sure thing! Thanks so much for your contribution

**Comment by bsr3000** [comment]
@marceloFA no problem, manually checked it worked

also to send emails on prod/staging environments you would need to change `EMAIL_BACKEND' to 
`EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'` in `settings.py` and add email provider credentials, thats it

**Pull request merged**
