### PR TITLE
Added: user profile and edit profile

### PR DESCRIPTION
**Pull request by srahnama**
#14 user profile and edit profile added!

### CODE REVIEW

**Comment by marceloFA** [comment]
That's so cool! Thanks so much for contributing. Would you mind putting some screenshots showing the html templates as an example of the changes you've made? @srahnama

**Comment by srahnama** [comment]
url : `profile/`
Screenshot from 2019-10-04 15-56-52

url : `profile/edit`

Screenshot from 2019-10-04 15-57-21

**Comment by marceloFA** [comment]
Great colab, thanks!!

**Comment by srahnama** [comment]
your welcome! :+1:

**Pull request merged**
